title: Tomatoast's Blog
author: 番茄吐司
email: thomasbyding@gmail.com
description: >
  有趣的编程话题和新鲜的生活评论。
baseurl: ""
url: "https://tomatoast.pw"
github_username:  thomasding
paginate: 10

excerpt_separator: <!--more-->

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
