title: 番茄吐司的饮食指南
author: 番茄吐司
email: thomasbyding@gmail.com
description: >
  有趣的编程话题和新鲜的生活评论。
baseurl: ""
url: "https://tomatoast.pw"
github_username:  thomasding

excerpt_separator: <!--more-->

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

isso:
  url: //tomatoast.pw/isso
