title: Tomatoast's Recipes
author: Tomatoast
email: thomasbyding@gmail.com
description: >
  Advanced programming topics and interesting reviews.
baseurl: ""
url: "https://tomatoast.pw"
github_username:  thomasding

excerpt_separator: <!--more-->

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

isso:
  url: //tomatoast.pw/isso
