title: Thomas Ding
email: thomasbyding@gmail.com
description: >
  Thomas Ding's Blog site covering many interesting programming techniques,
  including instruction-level optimization, C++ features and so on.
baseurl: ""
url: "http://www.thomasding.net"
github_username:  thomasding

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
