title: tding.in
author: Thomas Ding
email: thomasbyding@gmail.com
description: >
  Covering instruction-level optimization, C++ features, best practices and so
  many other interesting topics.
baseurl: ""
url: "http://tding.in"
github_username:  thomasding

excerpt_separator: <!--more-->

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: tding